config/routes.rb
Rails.application.routes.draw do
  

  root                'events#index'
   
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :invites
  resources :events, :only => [:new, :create, :show, :index]

 resources :users, :only => [:new, :create, :show]

end

app/models/attended_event.rb
class AttendedEvent < ActiveRecord::Base
  belongs_to :attendee, :class_name => "User"
  belongs_to :attended_event, :class_name => "Event"
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :invites, :foreign_key => :attended_event_id
  belongs_to :creator, :class_name => "User"
  has_many :attendees, :through => :invites
  
  scope			 :upcoming,    -> { where('date >= ?', DateTime.now).order('Date ASC') }
	scope      :past,        -> { where('date < ?', DateTime.now).order('Date DESC') }
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :attendee, :class_name => "User"
  belongs_to :attended_event, :class_name => "Event"
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :invites, :foreign_key => :attendee_id
  has_many :events, :foreign_key => :creator_id
  has_many :attended_events, :through => :invites
  attr_accessor :remember_token
  
 
  
  
 # Returns a random token.
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  # encrypts token
  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
   private
  # Remembers a user in the database for use in persistent sessions.
  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :logged_in_user, only: [:new, :create]
  def new
  
    @event = current_user.events.build
  end
  
  def index
     @events = Event.all
     @upcoming_events = Event.upcoming
     @prev_events = Event.past
  end
  
  def show
    @event = Event.find(params[:id])
    @creator = @event.creator
    @attendees = @event.attendees.all
    
  end
  
  def create
    @event = current_user.events.build(event_params)
    if @event.save
       redirect_to events_path
    else
      render 'new'
    end
   
  end
  
  
    private
   # Confirms a logged-in user.
   def logged_in_user
     unless logged_in?
       flash[:danger] = "Please log in."
       redirect_to login_url
     end
   end
    
   
   def event_params
      params.require(:event).permit(:date, :location, :description)  
   end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

	def create
		@event = Event.find(params[:invite][:attended_event_id])
		current_user.invites.create(attended_event_id: @event.id)
		redirect_to current_user
	end

	def destroy
		@invite = Invite.find(params[:id])
		current_user.invites.destroy(@invite)
		redirect_to current_user
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  
  def create
    user = User.find_by(username: params[:session][:username])
    if user 
        log_in user
        redirect_to user_path(user.id)
      
    else
      flash.now[:danger] = 'Invalid username'
      render 'new'
    end
  end
  
   def destroy
    log_out 
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @user = User.new
  end
  
  def create
    @user = User.new(user_params)
     if @user.save
      
      flash[:info] = "Registration successful!"
      render 'show'
    else
      render 'new'
    end
  
  end
  
  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.past
  end
  
  private

    def user_params
      params.require(:user).permit(:username, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
   # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
   def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
  current_user.update_attribute(:remember_token,
                                User.digest(User.new_remember_token))
  cookies.delete(:remember_token)
   
    session.delete(:user_id)
    @current_user = nil
    
  end

end
  
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li id="event-<%= event.id %>">
  
 
  <span class="content">
    <%= event.location %>
   
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(event.time) %> ago.
    
  </span>
</li>

app/views/events/index.html.erb
<% provide(:title, 'All Events') %>  
<div class="col-md-12">
 
       <% if  @upcoming_events.any? %>
         <h1>Upcoming Events</h1>
         <% @upcoming_events.each do |invite| %>
            <p>
          <p><%= link_to  invite.location, invite %></p>
              <p><%= invite.date.strftime("%B %d, %Y") %></p>
              <p><%= invite.description%></p>
            </p>
            <hr />
          <% end %>
        <% end %>

<% if  @prev_events.any? %>
       <h1>Past Events</h1>
       <% @prev_events.each do |invite| %>
          <p>
            
             <p><%= link_to  invite.location, invite %></p>
               <p><%= invite.date.strftime("%B %d, %Y") %></p>
              <p><%= invite.description%></p>
          </p>
          <hr />
        <% end %>
      <% end %> 

<% if logged_in? %>
 <%= link_to "Create an Event", new_event_path %>

<% end %>
</div>

app/views/events/new.html.erb
<% provide(:title, "Events") %>
<h1>Create an Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event, url: events_path) do |f| %>
      <p>
      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      </p>
      <p>
      <%= f.label :date %>
    
      <%= f.date_select :date, :order => [:month, :day, :year] %>
      </p>
      <p>
      <%= f.submit "Post", class: "btn btn-primary" %>
      </p>
  <% end %>
    
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.description) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Event Details</h1>
    <p><strong>Location:</strong> <%= @event.location %></p>
    <p><strong>Description:</strong> <%= @event.description %></p>
    <p><strong>Date:</strong> <%= @event.date.strftime("%B %d, %Y") %></p>
    <p><strong>Created by:</strong> <%= link_to  @creator.username, @creator  %></p>
    <% if logged_in? %>
      <% if @event.attendees.include?(current_user) %>
          <%= form_for(current_user.invites.find_by(attended_event_id: @event.id), :html => { :method => :delete }) do |f| %>
            <%= f.submit "Leave Event", class: "btn btn-danger" %>
          <% end %>
      <% else %> 
        <%= form_for(current_user.invites.build(attended_event_id: @event.id)) do |f| %>
            <%= f.hidden_field :attended_event_id, :value => @event.id %>
            <%= f.submit "Attend Event", class: "btn btn-success" %>
        <% end %>
      <% end %>
    <% end %>
          
  <% if @event.attendees.any? %>
      <div class="posts">
      <h1>Attendees</h1>
        
      <% @event.attendees.each do |attendee| %>
        <p>
          <p><%= link_to  attendee.username, attendee %></p>
          
        </p>
        <hr />
      <% end %>
    <% else %>
        No one is coming - will you be the first?
     <% end %>
  </div>
  
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
     <nav>
      <ul class="nav navbar-nav navbar-right">
       
        <li><%= link_to "Events", events_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Account", current_user %></li>
          <li><%= link_to "Create Event", new_event_path %></li>
          <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Create an Account", new_user_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class="container">
     <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
 
  
  <div class="col-md-12">
    <h1> <%= @user.username %></h1>
    <h2> <%= @user.email %></h2>
    <hr />
    <div class="events">
    <% if @user.events.any? %>
     
      <h1>Created Events </h1>
      <% @user.events.each do |event| %>
        <p>
          <p><%= link_to  event.location, event %></p>
          <p><%= event.date.strftime("%B %d, %Y") %></p>
          <p><%= event.description%></p>
        </p>
        <hr />
      <% end %>
    <% else %>
        <h3><%= @user.username %> has not created any events</h3>
     <% end %>
     
     
    <% if @user.invites.any?  %>
       <% if  @upcoming_events.any? %>
         <h1>Upcoming Events</h1>
         <% @upcoming_events.each do |invite| %>
            <p>
          <p><%= link_to  invite.location, invite %></p>
              <p><%= invite.date.strftime("%B %d, %Y") %></p>
              <p><%= invite.description%></p>
            </p>
            <hr />
          <% end %>
        <% end %>
       <% if  @prev_events.any? %>
       <h1>Past Events</h1>
       <% @prev_events.each do |invite| %>
          <p>
            
             <p><%= link_to  invite.location, invite %></p>
               <p><%= invite.date.strftime("%B %d, %Y") %></p>
              <p><%= invite.description%></p>
          </p>
          <hr />
        <% end %>
      <% end %> 
    <% else %>
          <h3><%= @user.username %> is not attending any events</h3>
    <% end %>
  </div>
  
</div>